CREATE SEQUENCE "SEQ_ID_ORDERS" START WITH 1 INCREMENT BY  1;

CREATE TABLE "ORDERS"(
    "ID" NUMBER(19,0),
    "USERNAME" VARCHAR2(255 CHAR) NOT NULL,
    "TOTAL_AMOUNT" NUMBER(8,2),
    PRIMARY KEY ("ID")
);

CREATE SEQUENCE "SEQ_ID_ORDERS_PRODUCT" START WITH 1 INCREMENT BY  1;

CREATE TABLE "ORDERS_PRODUCT"(
    "ID" NUMBER(19,0),
    "ORDERS_ID" NUMBER(19,0),
    "PRODUCT_ID" NUMBER(19,0),
    "QUANTITY" NUMBER(19,0),
    PRIMARY KEY ("ID"),
    CONSTRAINT FK_PRODUCT_ORDERS FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ID)
);