spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/payment-db
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: payment-service

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: false

axon:
  axonserver:
    servers: ${AXON_SERVER:localhost}
  amqp:
    exchange: axonExchange
  eventhandling:
    processors:
      person-aggregate:
        source: axonQueueMessageSource
  serializer:
    general: jackson
    events: jackson
    messages: Jackson

server:
  port: ${PORT:9003}
  servlet:
    context-path: /payment

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'