spring:
  application:
    name: user-service
    
server:
  port: ${PORT:9000}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'