
INSERT INTO APPLICATION_USER(ID, USERNAME, FIRST_NAME, LAST_NAME) VALUES(1, 'Nav001', 'Naveen', 'Bhardwaj');
INSERT INTO APPLICATION_USER(ID, USERNAME, FIRST_NAME, LAST_NAME) VALUES(2, 'Kap001', 'Kapil', 'Bhardwaj');