CREATE SEQUENCE "SEQ_ID_APPLICATION_USER" START WITH 1 INCREMENT BY  1;

CREATE TABLE "APPLICATION_USER"(
    "ID" NUMBER(19,0),
    "USERNAME" VARCHAR2(255 CHAR) NOT NULL,
    "FIRST_NAME" VARCHAR2(255 CHAR) NOT NULL,
    "LAST_NAME" VARCHAR2(255 CHAR) NOT NULL,
    PRIMARY KEY ("ID")
);