server:
  port: 8080

spring:
  application:
    name: application-cloud-gateway
  cloud:
    gateway:
      routes:
#        - id: UserService
#          uri: http://localhost:9000/
#          predicates:
#            - Path=/user/**
#        - id: ProductService
#          uri: http://localhost:9001/
#          predicates:
#            - Path=/product/**
        - id: OrderService
          uri: lb://order-service/
          predicates:
            - Path=/order/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'