spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/order-db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: order-service

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true

server:
  port: ${PORT:9002}
  servlet:
    context-path: /order

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'