spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/product-db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: product-service

server:
  port: ${PORT:9001}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'