CREATE SEQUENCE "SEQ_ID_PRODUCT" START WITH 1 INCREMENT BY  1;

CREATE TABLE "PRODUCT"(
    "ID" NUMBER(19,0),
    "NAME" VARCHAR2(255 CHAR) NOT NULL,
    "DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL,
    "PRICE" NUMBER(8,2) NOT NULL,
    PRIMARY KEY ("ID")
);